-- ── Google Form URL + Redemption Code system ─────────────────────────────────

-- 1. Add google_form_url to events
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS google_form_url TEXT;

-- 2. Make all new registrations auto-approved (no pending flow)
ALTER TABLE public.event_registrations
  ALTER COLUMN status SET DEFAULT 'approved';

-- 3. Drop the auto-coin trigger — coins now come via redemption codes only
DROP TRIGGER IF EXISTS trg_credit_registration_coins ON public.event_registrations;

-- 4. Reward codes generated by organisers after an event
CREATE TABLE IF NOT EXISTS public.event_reward_codes (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id         UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  code             TEXT NOT NULL UNIQUE,
  ace_coins_reward INTEGER NOT NULL DEFAULT 0 CHECK (ace_coins_reward >= 0),
  max_redemptions  INTEGER,                -- NULL = unlimited
  expires_at       TIMESTAMPTZ,
  created_by       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Track who redeemed which code (one redemption per user per code)
CREATE TABLE IF NOT EXISTS public.event_code_redemptions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code_id       UUID NOT NULL REFERENCES public.event_reward_codes(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  coins_awarded INTEGER NOT NULL DEFAULT 0,
  redeemed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (code_id, user_id)
);

-- 6. Coin transaction log (income = positive, expense = negative)
CREATE TABLE IF NOT EXISTS public.coin_transactions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount       INTEGER NOT NULL,
  description  TEXT NOT NULL,
  type         TEXT NOT NULL DEFAULT 'redemption',
  reference_id UUID,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE public.event_reward_codes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_code_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coin_transactions     ENABLE ROW LEVEL SECURITY;

-- event_reward_codes: anyone can read, only event owner or admin can insert/update/delete
DO $$ BEGIN CREATE POLICY "erc_select_all" ON public.event_reward_codes FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY "erc_insert_owner" ON public.event_reward_codes FOR INSERT WITH CHECK (
  created_by = auth.uid() AND (
    EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND submitter_user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND is_admin = true)
  )
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY "erc_delete_owner" ON public.event_reward_codes FOR DELETE USING (
  created_by = auth.uid()
  OR EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND is_admin = true)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- event_code_redemptions: users see their own, organisers see theirs
DO $$ BEGIN CREATE POLICY "ecr_select_own" ON public.event_code_redemptions FOR SELECT USING (
  user_id = auth.uid()
  OR EXISTS (
    SELECT 1 FROM public.event_reward_codes rc
    JOIN public.events e ON e.id = rc.event_id
    WHERE rc.id = code_id AND e.submitter_user_id = auth.uid()
  )
  OR EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND is_admin = true)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY "ecr_insert_own" ON public.event_code_redemptions FOR INSERT WITH CHECK (
  user_id = auth.uid()
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- coin_transactions: users see only their own
DO $$ BEGIN CREATE POLICY "ct_select_own" ON public.coin_transactions FOR SELECT USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE POLICY "ct_insert_own" ON public.coin_transactions FOR INSERT WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── RPC: redeem a reward code (atomic) ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.redeem_reward_code(
  p_code    TEXT,
  p_user_id UUID
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_code        event_reward_codes%ROWTYPE;
  v_redeem_count INTEGER;
  v_coins       INTEGER;
BEGIN
  -- Look up code (case-insensitive)
  SELECT * INTO v_code FROM public.event_reward_codes WHERE UPPER(code) = UPPER(p_code);
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid code.');
  END IF;

  -- Check expiry
  IF v_code.expires_at IS NOT NULL AND v_code.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This code has expired.');
  END IF;

  -- Check max redemptions
  IF v_code.max_redemptions IS NOT NULL THEN
    SELECT COUNT(*) INTO v_redeem_count FROM public.event_code_redemptions WHERE code_id = v_code.id;
    IF v_redeem_count >= v_code.max_redemptions THEN
      RETURN jsonb_build_object('ok', false, 'error', 'This code has reached its maximum redemptions.');
    END IF;
  END IF;

  -- Check already redeemed by this user
  IF EXISTS (SELECT 1 FROM public.event_code_redemptions WHERE code_id = v_code.id AND user_id = p_user_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'You have already redeemed this code.');
  END IF;

  v_coins := v_code.ace_coins_reward;

  -- Record redemption
  INSERT INTO public.event_code_redemptions (code_id, user_id, coins_awarded)
  VALUES (v_code.id, p_user_id, v_coins);

  -- Credit coins
  UPDATE public.profiles SET ace_coins = ace_coins + v_coins WHERE user_id = p_user_id;

  -- Log transaction
  INSERT INTO public.coin_transactions (user_id, amount, description, type, reference_id)
  VALUES (
    p_user_id,
    v_coins,
    (SELECT 'Event reward: ' || title FROM public.events WHERE id = v_code.event_id LIMIT 1),
    'redemption',
    v_code.id
  );

  RETURN jsonb_build_object('ok', true, 'coins', v_coins);
END;
$$;
